# Generated by Django 4.0.3 on 2022-12-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('image', models.CharField(default='https://dummyimage.com/640x360/fff/aaa', max_length=400)),
            ],
        ),
    ]
